### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [getelevar/gtm-monitoring-variables#2]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) We are seeing error "An unknown error has occurred, please try again." when we try to run the tests.

**Comment by Aaronkala** [comment]
Hey @praveena-pappu,

It looks like that error is caused by the default value on the `debugMode` field. The tests seem to have some kind of dependency on the template preview. If you clear the default value then all the tests should succeed.

Do you want me to modify the template to remove the default value altogether? I included it there to help the user, so they won't have to type it because it's always fixed.

Before | After
--- | ---
<img width="270" alt="Screenshot 2020-04-24 at 11 20 30" src="https://user-images.githubusercontent.com/9134893/80196500-cb3a7180-861d-11ea-973b-2587a060a58d.png"> | <img width="270" alt="Screenshot 2020-04-24 at 11 22 13" src="https://user-images.githubusercontent.com/9134893/80196844-2e2c0880-861e-11ea-9eec-0d24489dde33.png">
